/* ==========================================================================
   SHREE HANUMAN SUPER MARKET - Expanded Daily Essentials Products Dataset
   Includes Vegetables, Wafers/Biscuits, Sugar/Tea, Rice/Wheat, Oils & More
   Owner: Jitendra Bhanwarlal Unecha | Contact: 7083568189
   ========================================================================== */

const productsData = [
  // --- 1. SUGAR, TEA, WHEAT & RICE ESSENTIALS ---
  {
    id: "prod-1",
    name: "Aashirvaad Shuddha Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "10kg Bag",
    price: 410,
    unit: "bag",
    availability: "In Stock",
    badge: "Hot Deal",
    featuredHero: true,
    image: "images/wheat_atta.png",
    description: "100% pure wheat grain chakki fresh flour delivering soft, fluffy rotis and high dietary fiber."
  },
  {
    id: "prod-2",
    name: "Madhur Pure Crystal White Sugar",
    brand: "Madhur",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "5kg Saver Pack",
    price: 225,
    unit: "pack",
    availability: "In Stock",
    badge: "Sulphur Free",
    featuredHero: true,
    image: "images/sugar_pack.png",
    description: "Sulphur-free, untouched crystal white sugar refined with modern international standards."
  },
  {
    id: "prod-3",
    name: "Tata Tea Gold Premium Leaf Tea",
    brand: "Tata Tea",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "1kg Pack",
    price: 520,
    unit: "pack",
    availability: "In Stock",
    badge: "Rich Aroma",
    featuredHero: true,
    image: "images/tata_tea.png",
    description: "Exquisite blend of fine Assam tea leaves with gently rolled long leaves for rich taste."
  },
  {
    id: "prod-4",
    name: "Royal Traditional Basmati Rice",
    brand: "Royal India",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "25kg Premium Bag",
    price: 3200,
    unit: "bag",
    availability: "In Stock",
    badge: "Premium Grade",
    featuredHero: true,
    image: "images/basmati_rice.png",
    description: "Aged long-grain aromatic Basmati rice with exquisite fragrance and fluffy post-cooking texture."
  },
  {
    id: "prod-5",
    name: "Sona Masoori Raw Rice 25kg",
    brand: "Hanuman Select",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "25kg Wholesale Bag",
    price: 1450,
    unit: "bag",
    availability: "In Stock",
    badge: "Daily Essential",
    image: "images/basmati_rice.png",
    description: "Lightweight, aromatic medium-grain rice perfect for daily household consumption and catering."
  },
  {
    id: "prod-25",
    name: "Fortune Chakki Fresh Whole Wheat Atta",
    brand: "Fortune",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "10kg Bag",
    price: 395,
    unit: "bag",
    availability: "In Stock",
    badge: "Soft Rotis",
    image: "images/wheat_atta.png",
    description: "100% whole wheat chakki fresh atta for delicious and healthy daily rotis."
  },
  {
    id: "prod-26",
    name: "Daawat Rozana Super Basmati Rice",
    brand: "Daawat",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "5kg Saver Pack",
    price: 490,
    unit: "pack",
    availability: "In Stock",
    badge: "Long Grain",
    image: "images/basmati_rice.png",
    description: "Everyday Basmati rice with delightful aroma and delicious taste for your family."
  },
  {
    id: "prod-27",
    name: "Wagh Bakri Premium Leaf Tea",
    brand: "Wagh Bakri",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "500g Pack",
    price: 260,
    unit: "pack",
    availability: "In Stock",
    badge: "Strong Chai",
    image: "images/tata_tea.png",
    description: "Strong, aromatic Gujarat Assam leaf tea for perfect morning tea time."
  },

  // --- 2. FRESH VEGETABLES & FRUITS ---
  {
    id: "prod-6",
    name: "Fresh Red Onions (Kanda)",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "5kg Mesh Bag",
    price: 140,
    unit: "bag",
    availability: "In Stock",
    badge: "Farm Fresh",
    featuredHero: true,
    image: "images/fresh_vegetables.png",
    description: "Crisp, premium quality red onions sourced directly from Junnar and Nashik farms."
  },
  {
    id: "prod-7",
    name: "Fresh Potatoes (Batata)",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "5kg Sack",
    price: 130,
    unit: "sack",
    availability: "In Stock",
    badge: "Daily Fresh",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800",
    description: "Firm, clean cooking potatoes ideal for fries, curries, and daily sabzi."
  },
  {
    id: "prod-8",
    name: "Ripe Ratta Red Tomatoes",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "2kg Basket",
    price: 70,
    unit: "kg",
    availability: "In Stock",
    badge: "Juicy & Fresh",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800",
    description: "Naturally ripened juicy red tomatoes packed with vitamins and rich flavor."
  },
  {
    id: "prod-9",
    name: "Ginger, Garlic & Green Chili Trio",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1kg Combo (400g Ginger + 400g Garlic + 200g Chili)",
    price: 180,
    unit: "pack",
    availability: "In Stock",
    badge: "Essential Trio",
    image: "https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&q=80&w=800",
    description: "Freshly harvested aromatic ginger, firm white garlic cloves, and spicy green chillies."
  },
  {
    id: "prod-10",
    name: "Fresh Shimla Red Apples",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1kg Box",
    price: 160,
    unit: "kg",
    availability: "In Stock",
    badge: "Sweet & Crunchy",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800",
    description: "Juicy, sweet orchard-fresh Shimla red apples rich in antioxidants and fiber."
  },
  {
    id: "prod-28",
    name: "Fresh Yellow Lemons & Mint Combo",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "500g Pack",
    price: 45,
    unit: "pack",
    availability: "In Stock",
    badge: "Vitamin C",
    image: "images/fresh_vegetables.png",
    description: "Juicy yellow lemons and fragrant mint leaves for refreshing juices and cooking."
  },
  {
    id: "prod-29",
    name: "Organic Palak & Spinach Greens",
    brand: "Organic Farm",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1kg Bundle",
    price: 50,
    unit: "kg",
    availability: "In Stock",
    badge: "Iron Rich",
    image: "images/fresh_vegetables.png",
    description: "Tender green spinach leaves packed with vitamins, iron, and natural minerals."
  },
  {
    id: "prod-30",
    name: "Fresh Green Peas & Cauliflower Duo",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "2kg Combo",
    price: 110,
    unit: "pack",
    availability: "In Stock",
    badge: "Fresh Pick",
    image: "images/fresh_vegetables.png",
    description: "Sweet green peas pods and crisp white cauliflower heads for healthy meals."
  },

  // --- 3. WAFERS, BISCUITS & SNACKS ---
  {
    id: "prod-11",
    name: "Classic Potato Salted Wafers & Chips",
    brand: "Haldiram's / Balaji",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "Pack of 5 (5 x 100g)",
    price: 150,
    unit: "pack",
    availability: "In Stock",
    badge: "Crispy Crunch",
    featuredHero: true,
    image: "images/potato_chips.png",
    description: "Thin, crispy golden potato wafers seasoned with pure rock salt."
  },
  {
    id: "prod-12",
    name: "Britannia Good Day Butter Biscuits",
    brand: "Britannia",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "600g Super Saver Pack",
    price: 140,
    unit: "pack",
    availability: "In Stock",
    badge: "Tea Time",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=800",
    description: "Rich buttery cookies loaded with real butter and delightful crunch."
  },
  {
    id: "prod-13",
    name: "Chocolate & Vanilla Cream Wafers",
    brand: "Dukes / Pickwick",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "300g Twin Pack",
    price: 110,
    unit: "pack",
    availability: "In Stock",
    badge: "Kids Special",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=800",
    description: "Light, crunchy multi-layered wafer rolls filled with smooth chocolate and vanilla cream."
  },
  {
    id: "prod-14",
    name: "Haldiram's Nagpur Ratlami Sev & Bhujia",
    brand: "Haldiram's",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "400g Pack",
    price: 125,
    unit: "pack",
    availability: "In Stock",
    badge: "Spicy Crunch",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=800",
    description: "Authentic spicy chickpea flour fried noodles blended with cloves and black pepper."
  },
  {
    id: "prod-15",
    name: "Maggi 2-Minute Masala Noodles Mega Pack",
    brand: "Nestle Maggi",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "12 Single Packs Bundle (840g)",
    price: 168,
    unit: "bundle",
    availability: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800",
    description: "Iconic delicious masala instant noodles fortified with iron for a quick snack."
  },
  {
    id: "prod-31",
    name: "Balaji Simply Salted Potato Wafers",
    brand: "Balaji",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "Pack of 5 (5 x 85g)",
    price: 125,
    unit: "pack",
    availability: "In Stock",
    badge: "Crunchy",
    image: "images/potato_chips.png",
    description: "Classic salted crispy potato chips made from selected farm potatoes."
  },
  {
    id: "prod-32",
    name: "Parle-G Gold Glucose Biscuits Mega Pack",
    brand: "Parle",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "1kg Family Pack",
    price: 120,
    unit: "pack",
    availability: "In Stock",
    badge: "Energy Snack",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=800",
    description: "India's favorite glucose biscuit providing instant energy and nostalgia."
  },
  {
    id: "prod-33",
    name: "Kurkure Masala Munch Mega Saver Pack",
    brand: "Kurkure",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "350g Value Pack",
    price: 85,
    unit: "pack",
    availability: "In Stock",
    badge: "Chatpata",
    image: "images/potato_chips.png",
    description: "Tedhe medhe spicy chatpata corn curls cooked with authentic Indian spices."
  },

  // --- 4. COOKING OILS & GHEE ---
  {
    id: "prod-16",
    name: "Fortune Kachi Ghani Mustard Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "15L Canister / Wholesale Tin",
    price: 1850,
    unit: "tin",
    availability: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    description: "Cold-pressed pure kachi ghani mustard oil for authentic aroma and high culinary standards."
  },
  {
    id: "prod-17",
    name: "Fortune Refined Sunflower Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "15L Wholesale Pack (15 x 1L)",
    price: 1680,
    unit: "pack",
    availability: "In Stock",
    badge: "Popular",
    featuredHero: true,
    image: "images/sunflower_oil.png",
    description: "Light and healthy refined sunflower oil rich in Vitamin E, ideal for frying and daily cooking."
  },
  {
    id: "prod-18",
    name: "Amul Pure Cow Ghee",
    brand: "Amul",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "1L Tin",
    price: 640,
    unit: "tin",
    availability: "In Stock",
    badge: "Pure Ghee",
    image: "images/amul_ghee.png",
    description: "Traditional Amul cow ghee with granular texture, natural aroma, and rich flavor."
  },
  {
    id: "prod-34",
    name: "Gemini Refined Soybean Cooking Oil",
    brand: "Gemini",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "15L Box Container",
    price: 1620,
    unit: "pack",
    availability: "In Stock",
    badge: "Heart Healthy",
    image: "images/sunflower_oil.png",
    description: "Pure refined soybean cooking oil fortified with Vitamin A and D."
  },
  {
    id: "prod-35",
    name: "Saffola Gold Pro Healthy Heart Oil",
    brand: "Saffola",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "5L Can",
    price: 890,
    unit: "can",
    availability: "In Stock",
    badge: "Low Absorb",
    image: "images/sunflower_oil.png",
    description: "Dual seed technology oil with Oryzanol for superior heart health and immunity."
  },
  {
    id: "prod-36",
    name: "Gowardhan Pure Cow Ghee 1L Tin",
    brand: "Gowardhan",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "1L Tin",
    price: 670,
    unit: "tin",
    availability: "In Stock",
    badge: "Granular Ghee",
    image: "images/amul_ghee.png",
    description: "100% pure cow ghee churned from fresh cow milk with rich traditional taste."
  },

  // --- 5. PULSES & DAL ---
  {
    id: "prod-19",
    name: "Premium Unpolished Toor Dal (Arhar)",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "5kg Pack",
    price: 690,
    unit: "pack",
    availability: "In Stock",
    badge: "Direct Mill",
    image: "images/toor_dal.png",
    description: "Unpolished, nutrient-dense yellow toor dal free from artificial colors or oil coatings."
  },
  {
    id: "prod-20",
    name: "Pure Moong Dal Washed",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 240,
    unit: "pack",
    availability: "In Stock",
    badge: "High Protein",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800",
    description: "Easy to digest yellow moong dal, rich in protein and ideal for daily khichdi and soups."
  },
  {
    id: "prod-37",
    name: "Tata Sampann Unpolished Chana Dal",
    brand: "Tata Sampann",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "1kg Pack",
    price: 115,
    unit: "pack",
    availability: "In Stock",
    badge: "Rich Protein",
    image: "images/toor_dal.png",
    description: "Unpolished split Bengal gram dal curated by chef Sanjeev Kapoor."
  },
  {
    id: "prod-38",
    name: "Black Urad Dal Whole (Kali Dal)",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 250,
    unit: "pack",
    availability: "In Stock",
    badge: "Dal Makhani",
    image: "images/toor_dal.png",
    description: "Whole black gram lentils perfect for creamy Punjabi Dal Makhani."
  },
  {
    id: "prod-39",
    name: "Premium Chitra Rajma Kidney Beans",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 280,
    unit: "pack",
    availability: "In Stock",
    badge: "High Fiber",
    image: "images/toor_dal.png",
    description: "Superior quality spotted Jammu Chitra Rajma beans that cook soft and flavorful."
  },
  {
    id: "prod-40",
    name: "Pure Masoor Red Split Dal",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 190,
    unit: "pack",
    availability: "In Stock",
    badge: "Quick Cook",
    image: "images/toor_dal.png",
    description: "Quick cooking red split lentils loaded with natural iron and dietary fiber."
  },

  // --- 6. SPICES & DRY FRUITS ---
  {
    id: "prod-21",
    name: "Everest Pure Turmeric & Chili Powder Combo",
    brand: "Everest",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "1kg Combo Pack (500g Haldi + 500g Mirch)",
    price: 290,
    unit: "pack",
    availability: "In Stock",
    badge: "Best Value",
    featuredHero: true,
    image: "images/spices_combo.png",
    description: "High-curcumin turmeric powder and fiery red chili powder with natural oils preserved."
  },
  {
    id: "prod-41",
    name: "MDH Kitchen King & Garam Masala Duo",
    brand: "MDH",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "200g Combo Pack",
    price: 165,
    unit: "pack",
    availability: "In Stock",
    badge: "Authentic Spice",
    image: "images/spices_combo.png",
    description: "Aromatic blend of ground spices for rich North Indian curries and gravy."
  },
  {
    id: "prod-42",
    name: "Catch Cumin Powder & Cumin Seeds Combo",
    brand: "Catch",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "400g Pack",
    price: 190,
    unit: "pack",
    availability: "In Stock",
    badge: "Pure Jeera",
    image: "images/spices_combo.png",
    description: "Aromatic whole jeera seeds and finely ground cumin powder."
  },
  {
    id: "prod-43",
    name: "Tata Sampann Coriander Powder (Dhania)",
    brand: "Tata Sampann",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "500g Pack",
    price: 135,
    unit: "pack",
    availability: "In Stock",
    badge: "Natural Oils",
    image: "images/spices_combo.png",
    description: "Cooling aromatic coriander powder milled from whole green seeds."
  },
  {
    id: "prod-44",
    name: "Badshah Shahi Biryani Masala",
    brand: "Badshah",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "100g Pack",
    price: 75,
    unit: "pack",
    availability: "In Stock",
    badge: "Royal Taste",
    image: "images/spices_combo.png",
    description: "Royal spice mix for restaurant-style vegetable and Hyderabadi biryani."
  },

  // --- 7. DRY FRUITS & NUTS ---
  {
    id: "prod-22",
    name: "Royal Jumbo Cashews & Almonds Twin Pack",
    brand: "Hanuman Select",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "1kg Twin Pack (500g Kaju + 500g Badam)",
    price: 890,
    unit: "pack",
    availability: "In Stock",
    badge: "Premium Grade",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Whole W240 jumbo cashews and crunchy California almonds packed in vacuum zip pouches."
  },
  {
    id: "prod-46",
    name: "Nutraj Premium California Whole Almonds",
    brand: "Nutraj",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "1kg Vacuum Pack",
    price: 750,
    unit: "pack",
    availability: "In Stock",
    badge: "100% Natural",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Raw crunch California badam high in Vitamin E and healthy omega fats."
  },
  {
    id: "prod-47",
    name: "Happilo W240 Jumbo Cashew Nuts (Kaju)",
    brand: "Happilo",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Pouch",
    price: 490,
    unit: "pack",
    availability: "In Stock",
    badge: "King Size",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Large, buttery whole cashews handpicked for festive gifting and snacking."
  },
  {
    id: "prod-48",
    name: "Organic Green Sweet Raisins (Kishmish)",
    brand: "Organic Choice",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "1kg Pack",
    price: 320,
    unit: "pack",
    availability: "In Stock",
    badge: "Juicy Sweet",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Naturally sun-dried sweet green raisins free from added sugar or sulfur."
  },
  {
    id: "prod-49",
    name: "Royal Salted Roasted Pistachios (Pista)",
    brand: "Hanuman Select",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Pack",
    price: 540,
    unit: "pack",
    availability: "In Stock",
    badge: "Lightly Salted",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "In-shell Iranian roasted pistachios seasoned with rock salt."
  },

  // --- 8. CLEANING & HOUSEHOLD CARE ---
  {
    id: "prod-23",
    name: "Surf Excel Easy Wash Detergent Powder",
    brand: "Surf Excel",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "3kg Pack",
    price: 430,
    unit: "pack",
    availability: "In Stock",
    badge: "Tough Stain Removal",
    image: "https://images.unsplash.com/photo-1585832770485-e68a5fc88240?auto=format&fit=crop&q=80&w=800",
    description: "Superior stain removal power that dissolves fast and cleans clothes effortlessly."
  },
  {
    id: "prod-51",
    name: "Vim Lemon Dishwash Liquid Gel",
    brand: "Vim",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "750ml Bottle",
    price: 175,
    unit: "bottle",
    availability: "In Stock",
    badge: "Grease Removal",
    image: "https://images.unsplash.com/photo-1585832770485-e68a5fc88240?auto=format&fit=crop&q=80&w=800",
    description: "Concentrated lemon gel power that removes tough grease from utensils in one stroke."
  },
  {
    id: "prod-52",
    name: "Lizol Disinfectant Surface Cleaner Citrus",
    brand: "Lizol",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "2L Bottle",
    price: 340,
    unit: "bottle",
    availability: "In Stock",
    badge: "99.9% Germ Kill",
    image: "https://images.unsplash.com/photo-1585832770485-e68a5fc88240?auto=format&fit=crop&q=80&w=800",
    description: "10x better cleaning floor cleaner providing citrus freshness and germ protection."
  },
  {
    id: "prod-53",
    name: "Harpic Power Plus Toilet Cleaner Twin Pack",
    brand: "Harpic",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "2 x 1L Pack",
    price: 320,
    unit: "pack",
    availability: "In Stock",
    badge: "Max Clean",
    image: "https://images.unsplash.com/photo-1585832770485-e68a5fc88240?auto=format&fit=crop&q=80&w=800",
    description: "Thick formula toilet disinfectant gel that removes limescale and stains."
  },
  {
    id: "prod-54",
    name: "Colin Glass & Household Cleaner Spray",
    brand: "Colin",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "500ml Spray Bottle",
    price: 110,
    unit: "bottle",
    availability: "In Stock",
    badge: "Shine Boost",
    image: "https://images.unsplash.com/photo-1585832770485-e68a5fc88240?auto=format&fit=crop&q=80&w=800",
    description: "Streak-free glass cleaner spray for windows, mirrors, appliances, and tables."
  },

  // --- 9. PERSONAL CARE & HYGIENE ---
  {
    id: "prod-24",
    name: "Dettol Original Bath Soap Multipack",
    brand: "Dettol",
    category: "personal",
    categoryLabel: "Personal Care",
    weight: "5 x 125g Pack",
    price: 245,
    unit: "pack",
    availability: "In Stock",
    badge: "Germ Protection",
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f9c3?auto=format&fit=crop&q=80&w=800",
    description: "Trusted germ protection soap providing 99.9% protection with fresh pine fragrance."
  },
  {
    id: "prod-55",
    name: "Colgate Strong Teeth Toothpaste Family Saver",
    brand: "Colgate",
    category: "personal",
    categoryLabel: "Personal Care",
    weight: "500g Saver Pack (2x250g)",
    price: 230,
    unit: "pack",
    availability: "In Stock",
    badge: "Amino Power",
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f9c3?auto=format&fit=crop&q=80&w=800",
    description: "Calcium and Amino Power formula that strengthens teeth naturally."
  },
  {
    id: "prod-56",
    name: "Clinic Plus Strong & Long Health Shampoo",
    brand: "Clinic Plus",
    category: "personal",
    categoryLabel: "Personal Care",
    weight: "650ml Bottle",
    price: 320,
    unit: "bottle",
    availability: "In Stock",
    badge: "Milk Protein",
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f9c3?auto=format&fit=crop&q=80&w=800",
    description: "Enriched with milk protein for strong, healthy, and shiny hair."
  },
  {
    id: "prod-57",
    name: "Nivea Soft Moisturizing Cream Tub",
    brand: "Nivea",
    category: "personal",
    categoryLabel: "Personal Care",
    weight: "300ml Tub",
    price: 360,
    unit: "tub",
    availability: "In Stock",
    badge: "Jojoba Oil",
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f9c3?auto=format&fit=crop&q=80&w=800",
    description: "Non-greasy light moisturizing cream with Vitamin E and Jojoba oil."
  },
  {
    id: "prod-58",
    name: "Savlon Antiseptic Disinfectant Liquid",
    brand: "Savlon",
    category: "personal",
    categoryLabel: "Personal Care",
    weight: "1L Bottle",
    price: 215,
    unit: "bottle",
    availability: "In Stock",
    badge: "Doctor Recommended",
    image: "https://images.unsplash.com/photo-1607006482602-76ca0fd2f9c3?auto=format&fit=crop&q=80&w=800",
    description: "Effective antiseptic protection for wound care, bathing, and laundry."
  },

  // --- 10. BEST VALUE HOT DEALS & RATION KITS ---
  {
    id: "prod-59",
    name: "Hanuman Monthly Grocery Ration Mega Pack",
    brand: "Hanuman Super Combo",
    category: "best_value",
    categoryLabel: "Best Value Hot Deals",
    weight: "45kg Mega Combo Pack",
    price: 4999,
    unit: "combo",
    availability: "In Stock",
    badge: "Super Saver 25%",
    featuredHero: true,
    image: "images/wheat_atta.png",
    description: "Complete monthly grocery kit: 10kg Atta + 10kg Rice + 5kg Sugar + 2kg Toor Dal + 2L Sunflower Oil + Spices & Snacks!"
  },
  {
    id: "prod-60",
    name: "Farm Fresh Seasonal Vegetable Family Basket",
    brand: "Farm Fresh",
    category: "best_value",
    categoryLabel: "Best Value Hot Deals",
    weight: "10kg Assorted Basket",
    price: 399,
    unit: "basket",
    availability: "In Stock",
    badge: "Direct Farm",
    image: "images/fresh_vegetables.png",
    description: "3kg Onions + 3kg Potatoes + 2kg Tomatoes + 1kg Ginger/Garlic/Chili + 1kg Seasonal Greens."
  }
];

// Load Custom Products from localStorage
const CUSTOM_PRODUCTS_KEY = 'shree_hanuman_custom_products_v1';
try {
  const savedCustomProds = localStorage.getItem(CUSTOM_PRODUCTS_KEY);
  if (savedCustomProds) {
    const parsed = JSON.parse(savedCustomProds);
    if (Array.isArray(parsed)) {
      productsData.push(...parsed);
    }
  }
} catch (e) {
  console.warn("Could not load custom products from localStorage", e);
}

// Function to add new product dynamically
function addNewProductToDataset(prodObj) {
  productsData.unshift(prodObj);

  try {
    const existingCustom = JSON.parse(localStorage.getItem(CUSTOM_PRODUCTS_KEY) || '[]');
    existingCustom.unshift(prodObj);
    localStorage.setItem(CUSTOM_PRODUCTS_KEY, JSON.stringify(existingCustom));
  } catch (e) {
    console.error("Failed to save custom product to localStorage", e);
  }
}


