/* ==========================================================================
   SHREE HANUMAN SUPER MARKET - Expanded Daily Essentials Products Dataset
   Includes Vegetables, Wafers/Biscuits, Sugar/Tea, Rice/Wheat, Oils & More
   Owner: Jitendra Bhanwarlal Unecha | Contact: 7083568189
   ========================================================================== */

const productsData = [
  // --- 1. SUGAR, TEA, WHEAT & RICE (8 Products) ---
  {
    id: "prod-1",
    name: "Aashirvaad Shuddha Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "10kg Bag",
    price: 410,
    unit: "bag",
    availability: "In Stock",
    badge: "Hot Deal",
    featuredHero: true,
    image: "images/wheat_atta.png",
    description: "100% pure wheat grain chakki fresh flour delivering soft, fluffy rotis and high dietary fiber."
  },
  {
    id: "prod-2",
    name: "Madhur Pure Crystal White Sugar",
    brand: "Madhur",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "5kg Saver Pack",
    price: 225,
    unit: "pack",
    availability: "In Stock",
    badge: "Sulphur Free",
    featuredHero: true,
    image: "images/white_sugar.png",
    description: "Sulphur-free, untouched crystal white sugar refined with modern international standards."
  },
  {
    id: "prod-3",
    name: "Tata Tea Gold Premium Leaf Tea",
    brand: "Tata Tea",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "1kg Pack",
    price: 520,
    unit: "pack",
    availability: "In Stock",
    badge: "Rich Aroma",
    featuredHero: true,
    image: "images/tea_pack.png",
    description: "Exquisite blend of fine Assam tea leaves with gently rolled long leaves for rich taste."
  },
  {
    id: "prod-4",
    name: "Royal Traditional Basmati Rice",
    brand: "Royal India",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "25kg Premium Bag",
    price: 3200,
    unit: "bag",
    availability: "In Stock",
    badge: "Premium Grade",
    featuredHero: true,
    image: "images/basmati_rice.png",
    description: "Aged long-grain aromatic Basmati rice with exquisite fragrance and fluffy post-cooking texture."
  },
  {
    id: "prod-5",
    name: "Sona Masoori Raw Rice 25kg",
    brand: "Hanuman Select",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "25kg Wholesale Bag",
    price: 1450,
    unit: "bag",
    availability: "In Stock",
    badge: "Daily Essential",
    image: "images/basmati_rice.png",
    description: "Lightweight, aromatic medium-grain rice perfect for daily household consumption and catering."
  },
  {
    id: "prod-6",
    name: "Brooke Bond Red Label Natural Care Tea",
    brand: "Red Label",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "500g Pack",
    price: 310,
    unit: "pack",
    availability: "In Stock",
    badge: "Ayurvedic Blend",
    image: "images/tea_pack.png",
    description: "Blend of 5 Ayurvedic ingredients - Tulsi, Ashwagandha, Mulethi, Ginger & Cardamom."
  },
  {
    id: "prod-7",
    name: "Daawat Rozana Super Basmati Rice",
    brand: "Daawat",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "5kg Pack",
    price: 490,
    unit: "pack",
    availability: "In Stock",
    badge: "Best Seller",
    image: "images/basmati_rice.png",
    description: "Flavorful medium-long Basmati grains ideal for daily pulao, fried rice, and biryani."
  },
  {
    id: "prod-8",
    name: "Pillsbury Chakki Fresh Whole Wheat Atta",
    brand: "Pillsbury",
    category: "sugar_tea",
    categoryLabel: "Sugar, Tea, Wheat & Rice",
    weight: "5kg Bag",
    price: 215,
    unit: "bag",
    availability: "In Stock",
    badge: "Soft Rotis",
    image: "images/wheat_atta.png",
    description: "100% whole wheat grain ground fresh to retain natural wheat germ, bran, and fiber."
  },

  // --- 2. FRESH VEGETABLES & FRUITS (8 Products) ---
  {
    id: "prod-9",
    name: "Fresh Red Onions (Kanda)",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "5kg Mesh Bag",
    price: 140,
    unit: "bag",
    availability: "In Stock",
    badge: "Farm Fresh",
    featuredHero: true,
    image: "images/fresh_vegetables.png",
    description: "Crisp, premium quality red onions sourced directly from Junnar and Nashik farms."
  },
  {
    id: "prod-10",
    name: "Fresh Potatoes (Batata)",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "5kg Sack",
    price: 130,
    unit: "sack",
    availability: "In Stock",
    badge: "Daily Fresh",
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=800",
    description: "Firm, clean cooking potatoes ideal for fries, curries, and daily sabzi."
  },
  {
    id: "prod-11",
    name: "Ripe Ratta Red Tomatoes",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "2kg Basket",
    price: 70,
    unit: "kg",
    availability: "In Stock",
    badge: "Juicy & Fresh",
    image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800",
    description: "Naturally ripened juicy red tomatoes packed with vitamins and rich flavor."
  },
  {
    id: "prod-12",
    name: "Ginger, Garlic & Green Chili Trio",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1kg Combo (400g Ginger + 400g Garlic + 200g Chili)",
    price: 180,
    unit: "pack",
    availability: "In Stock",
    badge: "Essential Trio",
    image: "https://images.unsplash.com/photo-1608797178974-15b35a64ede9?auto=format&fit=crop&q=80&w=800",
    description: "Freshly harvested aromatic ginger, firm white garlic cloves, and spicy green chillies."
  },
  {
    id: "prod-13",
    name: "Fresh Shimla Red Apples",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1kg Box",
    price: 160,
    unit: "kg",
    availability: "In Stock",
    badge: "Sweet & Crunchy",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=800",
    description: "Juicy, sweet orchard-fresh Shimla red apples rich in antioxidants and fiber."
  },
  {
    id: "prod-14",
    name: "Fresh Golden Robusta Bananas",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "1 Dozen (12 Pcs)",
    price: 60,
    unit: "dozen",
    availability: "In Stock",
    badge: "Potassium Rich",
    image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=800",
    description: "Naturally ripened sweet Robusta bananas perfect for breakfast and energy snacks."
  },
  {
    id: "prod-15",
    name: "Fresh Juicy Yellow Lemons",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "500g Pack (approx 10-12 lemons)",
    price: 45,
    unit: "pack",
    availability: "In Stock",
    badge: "Vitamin C",
    image: "https://images.unsplash.com/photo-1534531141161-e41d133a8ad7?auto=format&fit=crop&q=80&w=800",
    description: "Tangy, juicy yellow lemons for fresh lemonade, salads, and pickles."
  },
  {
    id: "prod-16",
    name: "Fresh Green Coriander & Mint Combo",
    brand: "Farm Fresh",
    category: "vegetables",
    categoryLabel: "Fresh Vegetables & Fruits",
    weight: "200g Bundle",
    price: 30,
    unit: "bundle",
    availability: "In Stock",
    badge: "Herb Special",
    image: "https://images.unsplash.com/photo-1588879460405-566bc9d1e39a?auto=format&fit=crop&q=80&w=800",
    description: "Aromatic fresh green coriander leaves paired with crisp mint leaves for chutneys."
  },

  // --- 3. WAFERS, BISCUITS & SNACKS (8 Products) ---
  {
    id: "prod-17",
    name: "Balaji Classic Salted Wafers Pack",
    brand: "Balaji Wafers",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "Pack of 5 (5 x 100g)",
    price: 150,
    unit: "pack",
    availability: "In Stock",
    badge: "Crispy Crunch",
    featuredHero: true,
    image: "images/potato_chips.png",
    description: "Thin, crispy golden potato wafers seasoned with pure rock salt."
  },
  {
    id: "prod-18",
    name: "Britannia Good Day Butter Biscuits",
    brand: "Britannia",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "600g Super Saver Pack",
    price: 140,
    unit: "pack",
    availability: "In Stock",
    badge: "Tea Time",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=800",
    description: "Rich buttery cookies loaded with real butter and delightful crunch."
  },
  {
    id: "prod-19",
    name: "Chocolate & Vanilla Cream Wafers",
    brand: "Dukes",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "300g Twin Pack",
    price: 110,
    unit: "pack",
    availability: "In Stock",
    badge: "Kids Special",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=800",
    description: "Light, crunchy multi-layered wafer rolls filled with smooth chocolate and vanilla cream."
  },
  {
    id: "prod-20",
    name: "Haldiram's Nagpur Ratlami Sev & Bhujia",
    brand: "Haldiram's",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "400g Pack",
    price: 125,
    unit: "pack",
    availability: "In Stock",
    badge: "Spicy Crunch",
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=800",
    description: "Authentic spicy chickpea flour fried noodles blended with cloves and black pepper."
  },
  {
    id: "prod-21",
    name: "Maggi 2-Minute Masala Noodles Mega Pack",
    brand: "Nestle Maggi",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "12 Single Packs Bundle (840g)",
    price: 168,
    unit: "bundle",
    availability: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&q=80&w=800",
    description: "Iconic delicious masala instant noodles fortified with iron for a quick snack."
  },
  {
    id: "prod-22",
    name: "Parle-G Gold Glucose Biscuits Mega Pack",
    brand: "Parle",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "1kg Family Pack",
    price: 130,
    unit: "pack",
    availability: "In Stock",
    badge: "Classic Energy",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=800",
    description: "India's favorite glucose biscuit filled with energy, wheat, and milk nutrients."
  },
  {
    id: "prod-23",
    name: "Cadbury Oreo Vanilla Cream Biscuits",
    brand: "Cadbury Oreo",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "300g Combo Pack",
    price: 105,
    unit: "pack",
    availability: "In Stock",
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&q=80&w=800",
    description: "Rich dark chocolate cookie sandwich with smooth vanilla cream center."
  },
  {
    id: "prod-24",
    name: "Kurkure Masala Munch Spicy Crunch",
    brand: "Kurkure",
    category: "wafers_snacks",
    categoryLabel: "Wafers, Biscuits & Snacks",
    weight: "Pack of 4 (4 x 90g)",
    price: 80,
    unit: "pack",
    availability: "In Stock",
    badge: "Chatpata Taste",
    image: "images/potato_chips.png",
    description: "Crunchy corn-rice snack seasoned with traditional Indian spices and tangy flavors."
  },

  // --- 4. COOKING OILS & GHEE (6 Products) ---
  {
    id: "prod-25",
    name: "Fortune Kachi Ghani Mustard Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "15L Canister / Wholesale Tin",
    price: 1850,
    unit: "tin",
    availability: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    description: "Cold-pressed pure kachi ghani mustard oil for authentic aroma and high culinary standards."
  },
  {
    id: "prod-26",
    name: "Fortune Refined Sunflower Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "15L Wholesale Pack (15 x 1L)",
    price: 1680,
    unit: "pack",
    availability: "In Stock",
    badge: "Popular",
    featuredHero: true,
    image: "images/sunflower_oil.png",
    description: "Light and healthy refined sunflower oil rich in Vitamin E, ideal for frying and daily cooking."
  },
  {
    id: "prod-27",
    name: "Amul Pure Cow Ghee",
    brand: "Amul",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "1L Tin",
    price: 640,
    unit: "tin",
    availability: "In Stock",
    badge: "Pure Ghee",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800",
    description: "Traditional Amul cow ghee with granular texture, natural aroma, and rich flavor."
  },
  {
    id: "prod-28",
    name: "Gemini Refined Sunflower Oil",
    brand: "Gemini",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "5L Can",
    price: 610,
    unit: "can",
    availability: "In Stock",
    badge: "Nutri-Lock",
    image: "images/sunflower_oil.png",
    description: "Fortified with Vitamins A, D & E to keep your family healthy and active."
  },
  {
    id: "prod-29",
    name: "Saffola Gold Pro Healthy Heart Oil",
    brand: "Saffola",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "5L Jar",
    price: 780,
    unit: "jar",
    availability: "In Stock",
    badge: "Heart Care",
    image: "images/sunflower_oil.png",
    description: "Dual-seed technology oil with Oryzanol helping reduce bad cholesterol."
  },
  {
    id: "prod-30",
    name: "Gowardhan Pure Cow Ghee",
    brand: "Gowardhan",
    category: "oil",
    categoryLabel: "Cooking Oil & Ghee",
    weight: "1kg Jar",
    price: 660,
    unit: "jar",
    availability: "In Stock",
    badge: "Golden Aroma",
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=800",
    description: "100% cow ghee made from fresh cow milk with rich granular texture and mouthwatering aroma."
  },

  // --- 5. PULSES & DAL (6 Products) ---
  {
    id: "prod-31",
    name: "Premium Unpolished Toor Dal (Arhar)",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "5kg Pack",
    price: 690,
    unit: "pack",
    availability: "In Stock",
    badge: "Direct Mill",
    image: "images/pulses_dal.png",
    description: "Unpolished, nutrient-dense yellow toor dal free from artificial colors or oil coatings."
  },
  {
    id: "prod-32",
    name: "Pure Moong Dal Washed",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 240,
    unit: "pack",
    availability: "In Stock",
    badge: "High Protein",
    image: "images/pulses_dal.png",
    description: "Easy to digest yellow moong dal, rich in protein and ideal for daily khichdi and soups."
  },
  {
    id: "prod-33",
    name: "Tata Sampann Unpolished Chana Dal",
    brand: "Tata Sampann",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 210,
    unit: "pack",
    availability: "In Stock",
    badge: "Natural Taste",
    image: "images/pulses_dal.png",
    description: "Rich in natural flavor and protein, untouched by artificial polishing process."
  },
  {
    id: "prod-34",
    name: "Premium Black Urad Dal Whole",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 260,
    unit: "pack",
    availability: "In Stock",
    badge: "Rich Fiber",
    image: "images/pulses_dal.png",
    description: "Whole black urad dal for authentic Dal Makhani and nutritious home cooking."
  },
  {
    id: "prod-35",
    name: "Premium Rajma Jammu Red Kidney Beans",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 280,
    unit: "pack",
    availability: "In Stock",
    badge: "Soft Cooking",
    image: "images/pulses_dal.png",
    description: "Genuine red Jammu Rajma beans that cook soft and tender with rich curry gravy."
  },
  {
    id: "prod-36",
    name: "Premium Kabuli Chana Jumbo Chickpeas",
    brand: "Hanuman Select",
    category: "pulses",
    categoryLabel: "Pulses & Dal",
    weight: "2kg Pack",
    price: 250,
    unit: "pack",
    availability: "In Stock",
    badge: "Chole Special",
    image: "images/pulses_dal.png",
    description: "Jumbo sized white chick peas perfect for Restaurant style Chole Masala."
  },

  // --- 6. SPICES & MASALA (6 Products) ---
  {
    id: "prod-37",
    name: "Everest Pure Turmeric & Chili Powder Combo",
    brand: "Everest",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "1kg Combo Pack (500g Haldi + 500g Mirch)",
    price: 290,
    unit: "pack",
    availability: "In Stock",
    badge: "Best Value",
    featuredHero: true,
    image: "images/spices_combo.png",
    description: "High-curcumin turmeric powder and fiery red chili powder with natural oils preserved."
  },
  {
    id: "prod-38",
    name: "Catch Super Garam Masala Powder",
    brand: "Catch Spices",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "500g Pack",
    price: 230,
    unit: "pack",
    availability: "In Stock",
    badge: "Rich Flavor",
    image: "images/spices_combo.png",
    description: "Aromatic blend of roasted spices ground low-temperature to lock natural oils."
  },
  {
    id: "prod-39",
    name: "MDH Deggi Mirch Fiery Red Chili",
    brand: "MDH",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "500g Pack",
    price: 250,
    unit: "pack",
    availability: "In Stock",
    badge: "Natural Color",
    image: "images/spices_combo.png",
    description: "Blend of Indian red pepper providing vibrant red color and mild spicy kick."
  },
  {
    id: "prod-40",
    name: "Everest Dhana Jeera Coriander Cumin Powder",
    brand: "Everest",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "500g Pack",
    price: 160,
    unit: "pack",
    availability: "In Stock",
    badge: "Daily Cooking",
    image: "images/spices_combo.png",
    description: "Perfect blend of fragrant coriander and earthy cumin for curry thick gravy."
  },
  {
    id: "prod-41",
    name: "Ramdev Pure Whole Cumin Seeds (Jeera)",
    brand: "Ramdev",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "500g Pouch",
    price: 270,
    unit: "pack",
    availability: "In Stock",
    badge: "Pure Seeds",
    image: "images/spices_combo.png",
    description: "Cleaned whole cumin seeds with intense aromatic fragrance for tempering."
  },
  {
    id: "prod-42",
    name: "Badshah Kitchen King All-Purpose Masala",
    brand: "Badshah",
    category: "spices",
    categoryLabel: "Spices & Masala",
    weight: "250g Pack",
    price: 115,
    unit: "pack",
    availability: "In Stock",
    badge: "Master Taste",
    image: "images/spices_combo.png",
    description: "Versatile spice blend adding restaurant style taste to veg curries and paneer."
  },

  // --- 7. DRY FRUITS & NUTS (6 Products) ---
  {
    id: "prod-43",
    name: "Royal Jumbo Cashews & Almonds Twin Pack",
    brand: "Hanuman Select",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "1kg Twin Pack (500g Kaju + 500g Badam)",
    price: 890,
    unit: "pack",
    availability: "In Stock",
    badge: "Premium Grade",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Whole W240 jumbo cashews and crunchy California almonds packed in vacuum zip pouches."
  },
  {
    id: "prod-44",
    name: "Nutraj Premium California Almonds",
    brand: "Nutraj",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Zip Pouch",
    price: 430,
    unit: "pack",
    availability: "In Stock",
    badge: "Heart Healthy",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "100% natural, crunchy California almonds rich in Vitamin E, protein, and dietary fiber."
  },
  {
    id: "prod-45",
    name: "Happilo Premium Whole W240 Cashews",
    brand: "Happilo",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Pouch",
    price: 490,
    unit: "pack",
    availability: "In Stock",
    badge: "Super Jumbo",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Large, buttery whole cashews handpicked for snacking and sweet preparation."
  },
  {
    id: "prod-46",
    name: "Tulsi Afghan Green Kishmish Raisins",
    brand: "Tulsi",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Pack",
    price: 240,
    unit: "pack",
    availability: "In Stock",
    badge: "Sweet & Juicy",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Seedless long green Afghan raisins rich in iron and natural sweetness."
  },
  {
    id: "prod-47",
    name: "Nutraj Royal Walnut Kernels (Akhrot)",
    brand: "Nutraj",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Vacuum Pack",
    price: 540,
    unit: "pack",
    availability: "In Stock",
    badge: "Brain Booster",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Chilean extra light walnut kernels rich in Omega-3 fatty acids."
  },
  {
    id: "prod-48",
    name: "Happilo Roasted & Salted Pistachios",
    brand: "Happilo",
    category: "dryfruits",
    categoryLabel: "Dry Fruits & Nuts",
    weight: "500g Pouch",
    price: 580,
    unit: "pack",
    availability: "In Stock",
    badge: "Gourmet Snack",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "California inshell roasted pistachios lightly salted for crisp healthy snacking."
  },

  // --- 8. CLEANING & PERSONAL CARE (10 Products) ---
  {
    id: "prod-49",
    name: "Surf Excel Easy Wash Detergent Powder",
    brand: "Surf Excel",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "3kg Pack",
    price: 430,
    unit: "pack",
    availability: "In Stock",
    badge: "Tough Stain Removal",
    image: "images/cleaning_essentials.png",
    description: "Superior stain removal power that dissolves fast and cleans clothes effortlessly."
  },
  {
    id: "prod-49b",
    name: "Harpic Power Plus Disinfectant Toilet Cleaner",
    brand: "Harpic",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "1L Bottle",
    price: 195,
    unit: "bottle",
    availability: "In Stock",
    badge: "10x Cleaning",
    image: "images/cleaning_essentials.png",
    description: "Kills 99.9% of germs and removes tough yellow stains for a sparkling clean toilet bowl."
  },
  {
    id: "prod-50",
    name: "Dettol Original Bath Soap Multipack",
    brand: "Dettol",
    category: "cleaning",
    categoryLabel: "Personal Care",
    weight: "5 x 125g Pack",
    price: 245,
    unit: "pack",
    availability: "In Stock",
    badge: "Germ Protection",
    image: "images/personal_care.png",
    description: "Trusted germ protection soap providing 99.9% protection with fresh pine fragrance."
  },
  {
    id: "prod-50b",
    name: "Lizol Citrus Disinfectant Floor Cleaner",
    brand: "Lizol",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "1L Saver Pack",
    price: 215,
    unit: "bottle",
    availability: "In Stock",
    badge: "99.9% Germ Kill",
    image: "images/cleaning_essentials.png",
    description: "Triple action disinfectant surface cleaner leaving floors 10x cleaner with fresh citrus fragrance."
  },
  {
    id: "prod-51",
    name: "Ariel Matic Front & Top Load Detergent",
    brand: "Ariel",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "4kg Mega Saver",
    price: 680,
    unit: "pack",
    availability: "In Stock",
    badge: "Brilliant Shine",
    image: "images/cleaning_essentials.png",
    description: "Designed for washing machines to remove tough stains in 1 wash."
  },
  {
    id: "prod-51b",
    name: "Comfort After Wash Morning Fresh Fabric Conditioner",
    brand: "Comfort",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "1L Pack",
    price: 220,
    unit: "bottle",
    availability: "In Stock",
    badge: "Long Lasting Freshness",
    image: "images/cleaning_essentials.png",
    description: "Provides softness, long-lasting fragrance, and fabric color protection after every wash."
  },
  {
    id: "prod-52",
    name: "Vim Lemon Dishwash Gel Refill",
    brand: "Vim",
    category: "cleaning",
    categoryLabel: "Cleaning & Household",
    weight: "1.5L Bottle",
    price: 240,
    unit: "bottle",
    availability: "In Stock",
    badge: "Grease Cutter",
    image: "images/cleaning_essentials.png",
    description: "Concentrated lemon gel that cleans tough grease on utensils without scratching."
  },
  {
    id: "prod-52b",
    name: "Dettol Skincare Moisturizing Liquid Handwash Refill",
    brand: "Dettol",
    category: "cleaning",
    categoryLabel: "Personal Care",
    weight: "1.5L Pouch Pack",
    price: 235,
    unit: "pack",
    availability: "In Stock",
    badge: "Soft & Gentle",
    image: "images/personal_care.png",
    description: "pH-balanced moisturizing handwash refill pouch that protects against 100 illness-causing germs."
  },
  {
    id: "prod-53",
    name: "Dove Cream Beauty Bathing Bar",
    brand: "Dove",
    category: "cleaning",
    categoryLabel: "Personal Care",
    weight: "5 x 125g Pack",
    price: 290,
    unit: "pack",
    availability: "In Stock",
    badge: "Moisturizing",
    image: "images/personal_care.png",
    description: "Contains 1/4 moisturizing cream for soft, smooth, radiant skin."
  },
  {
    id: "prod-54",
    name: "Colgate Strong Teeth Toothpaste Twin Pack",
    brand: "Colgate",
    category: "cleaning",
    categoryLabel: "Personal Care",
    weight: "500g Combo (2 x 250g)",
    price: 215,
    unit: "pack",
    availability: "In Stock",
    badge: "Calcium Boost",
    image: "images/personal_care.png",
    description: "Amino Power formula that adds natural calcium to your teeth for 2x stronger teeth."
  },

  // --- 9. BEST VALUE MEGA DEALS (6 Products) ---
  {
    id: "prod-55",
    name: "Monthly Household Super Saver Grocery Kit",
    brand: "Hanuman Combo",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "Kit (10kg Atta + 5kg Sugar + 5L Oil + 1kg Tea)",
    price: 1790,
    unit: "kit",
    availability: "In Stock",
    badge: "Mega Saver",
    image: "images/wheat_atta.png",
    description: "Complete household monthly grocery package saving up to ₹350."
  },
  {
    id: "prod-56",
    name: "Farm Fresh Veggie & Salad Family Basket",
    brand: "Farm Fresh",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "15kg Family Box",
    price: 490,
    unit: "box",
    availability: "In Stock",
    badge: "Fresh Box",
    image: "images/fresh_vegetables.png",
    description: "Weekly fresh vegetable basket containing Onions, Potatoes, Tomatoes, Ginger, Chili & Greens."
  },
  {
    id: "prod-57",
    name: "Tea Time Snack Lovers Combo Bundle",
    brand: "Snack Special",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "Combo Pack (Tea + Good Day + Wafers + Bhujia)",
    price: 420,
    unit: "pack",
    availability: "In Stock",
    badge: "Tea Special",
    image: "images/tea_pack.png",
    description: "Perfect tea time snack combo for evening family treats."
  },
  {
    id: "prod-58",
    name: "Pure Sunflower Oil & Cow Ghee Duo Pack",
    brand: "Kitchen Combo",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "Duo (5L Sunflower Oil + 1L Cow Ghee)",
    price: 1190,
    unit: "pack",
    availability: "In Stock",
    badge: "Pure Cooking",
    image: "images/sunflower_oil.png",
    description: "Health combo of Fortune Sunflower Oil and Amul Cow Ghee."
  },
  {
    id: "prod-59",
    name: "Panchratna Dal & Spices Kitchen Pack",
    brand: "Spice Master",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "5kg Combo (Toor + Moong + Chana + Everest Haldi + Mirch)",
    price: 750,
    unit: "pack",
    availability: "In Stock",
    badge: "High Protein",
    image: "images/pulses_dal.png",
    description: "Complete dal and spice kit for authentic daily Indian cooking."
  },
  {
    id: "prod-60",
    name: "Family Munchies & Potato Chips Party Pack",
    brand: "Party Bundle",
    category: "best_value",
    categoryLabel: "Best Value Deals",
    weight: "Mega Bundle (Wafers + Kurkure + Oreo + Maggi)",
    price: 390,
    unit: "bundle",
    availability: "In Stock",
    badge: "Party Pack",
    image: "images/potato_chips.png",
    description: "Fun party bundle packed with crisps, biscuits, and instant noodles."
  }
];

// Load Custom Products from localStorage
const CUSTOM_PRODUCTS_KEY = 'shree_hanuman_custom_products_v1';
try {
  const savedCustomProds = localStorage.getItem(CUSTOM_PRODUCTS_KEY);
  if (savedCustomProds) {
    const parsed = JSON.parse(savedCustomProds);
    if (Array.isArray(parsed)) {
      productsData.push(...parsed);
    }
  }
} catch (e) {
  console.warn("Could not load custom products from localStorage", e);
}

// Function to add new product dynamically
function addNewProductToDataset(prodObj) {
  productsData.unshift(prodObj);

  try {
    const existingCustom = JSON.parse(localStorage.getItem(CUSTOM_PRODUCTS_KEY) || '[]');
    existingCustom.unshift(prodObj);
    localStorage.setItem(CUSTOM_PRODUCTS_KEY, JSON.stringify(existingCustom));
  } catch (e) {
    console.error("Failed to save custom product to localStorage", e);
  }
}

