/* ==========================================================================
   V & B ENTERPRISES - Wholesale Products Dataset
   Owner: Basheer Sayed | Easily edit product details and wholesale prices below.
   ========================================================================== */

const productsData = [
  {
    id: "prod-1",
    name: "Fortune Kachi Ghani Mustard Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil",
    weight: "15L Canister / Wholesale Tin",
    price: 1850,
    unit: "tin",
    availability: "In Stock",
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    description: "Cold-pressed pure kachi ghani mustard oil for authentic aroma and high culinary standards."
  },
  {
    id: "prod-2",
    name: "Fortune Refined Sunflower Oil",
    brand: "Fortune",
    category: "oil",
    categoryLabel: "Cooking Oil",
    weight: "15L Wholesale Pack",
    price: 1680,
    unit: "pack",
    availability: "In Stock",
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1620706857370-e1b9770e8bb1?auto=format&fit=crop&q=80&w=800",
    description: "Light and healthy refined sunflower oil rich in Vitamin E, ideal for frying and daily cooking."
  },
  {
    id: "prod-3",
    name: "Tata Salt Vacuum Evaporated",
    brand: "Tata Salt",
    category: "salt",
    categoryLabel: "Salt",
    weight: "50kg Commercial Wholesale Bag (50 x 1kg)",
    price: 980,
    unit: "bag",
    availability: "In Stock",
    badge: "Essential",
    image: "https://images.unsplash.com/photo-1518110168401-f2877ee2e88d?auto=format&fit=crop&q=80&w=800",
    description: "India's trusted vacuum evaporated iodized salt ensures purity, consistency, and health safety."
  },
  {
    id: "prod-4",
    name: "Everest Pure Turmeric & Spice Combo",
    brand: "Everest",
    category: "spices",
    categoryLabel: "Spices",
    weight: "10kg Bulk Commercial Pack",
    price: 2450,
    unit: "pack",
    availability: "In Stock",
    badge: "High Margin",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800",
    description: "100% natural aromatic spices finely ground under strict hygienic processing."
  },
  {
    id: "prod-5",
    name: "Royal Traditional Basmati Rice",
    brand: "Royal India",
    category: "rice",
    categoryLabel: "Rice",
    weight: "25kg Premium Jute Bag",
    price: 3200,
    unit: "bag",
    availability: "In Stock",
    badge: "Premium Grade",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
    description: "Aged long-grain aromatic Basmati rice with exquisite fragrance and fluffy post-cooking texture."
  },
  {
    id: "prod-6",
    name: "Madhur Pure Crystal White Sugar",
    brand: "Madhur",
    category: "sugar",
    categoryLabel: "Sugar",
    weight: "50kg Wholesale Bag",
    price: 2150,
    unit: "bag",
    availability: "In Stock",
    badge: "High Demand",
    image: "https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&q=80&w=800",
    description: "Sulphur-free, untouched crystal white sugar refined with modern international standards."
  },
  {
    id: "prod-7",
    name: "Aashirvaad Shuddha Whole Wheat Atta",
    brand: "Aashirvaad",
    category: "flour",
    categoryLabel: "Flour",
    weight: "50kg Wholesale Bundle (5 x 10kg)",
    price: 1820,
    unit: "bundle",
    availability: "In Stock",
    badge: "Top Seller",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800",
    description: "100% pure wheat grain chakki fresh flour delivering soft, fluffy rotis and high dietary fiber."
  },
  {
    id: "prod-8",
    name: "Premium Unpolished Toor Dal (Arhar)",
    brand: "V & B Select",
    category: "pulses",
    categoryLabel: "Pulses",
    weight: "30kg Wholesale Bag",
    price: 3850,
    unit: "bag",
    availability: "In Stock",
    badge: "Direct Mill",
    image: "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?auto=format&fit=crop&q=80&w=800",
    description: "Unpolished, nutrient-dense yellow toor dal free from artificial colors or oil coatings."
  },
  {
    id: "prod-9",
    name: "Royal Mixed Dry Fruits Crate",
    brand: "V & B Select",
    category: "dryfruits",
    categoryLabel: "Dry Fruits",
    weight: "10kg Wholesale Box (Cashews, Almonds, Raisins)",
    price: 6800,
    unit: "box",
    availability: "In Stock",
    badge: "Luxury Grade",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&q=80&w=800",
    description: "Hand-sorted jumbo cashews, California almonds, and golden raisins sealed for peak freshness."
  },
  {
    id: "prod-10",
    name: "Whole Red Chili & Garam Masala Pack",
    brand: "V & B Spices",
    category: "spices",
    categoryLabel: "Spices",
    weight: "15kg Bulk Sack",
    price: 4200,
    unit: "sack",
    availability: "In Stock",
    badge: "Wholesale Value",
    image: "https://images.unsplash.com/photo-1509358211425-24d08ca35f65?auto=format&fit=crop&q=80&w=800",
    description: "Sun-dried fiery red chillies and whole spices sourced directly from trusted spice plantations."
  },
  {
    id: "prod-11",
    name: "Sona Masoori Raw Rice 25kg Bag",
    brand: "V & B Select",
    category: "rice",
    categoryLabel: "Rice",
    weight: "25kg Wholesale Bag",
    price: 1450,
    unit: "bag",
    availability: "In Stock",
    badge: "Daily Essential",
    image: "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&q=80&w=800",
    description: "Lightweight, aromatic medium-grain rice perfect for daily household consumption and catering."
  },
  {
    id: "prod-12",
    name: "Wholesale Grocery Retail Master Crate",
    brand: "V & B Enterprise",
    category: "grocery",
    categoryLabel: "Grocery Items",
    weight: "Assorted Retail Starter Bundle",
    price: 12500,
    unit: "crate",
    availability: "In Stock",
    badge: "Starter Crate",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=800",
    description: "Curated wholesale grocery assortment for newly opening supermarkets and retail outlets."
  }
];
